services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env:
      - MONGODB_URI
      - JWT_SECRET
      - PORT=8080
      - NODE_ENV=production
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    env:
      - REACT_APP_API_URL
    ports:
      - 80:80
    depends_on:
      - backend
